// Generates supabase/seed.sql from the app's bundled seed data
// (src/data/cards.js and src/data/content.js), keeping the database
// seed and the local fallback data in sync.
//
// Usage: npm run generate:seed

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { banks, categories, creditCards, extraCategoryAssignments, normalizeCards } from '../src/data/cards.js';
import {
  faqs,
  interestRates,
  reviews,
  eligibilityCriteria,
  cibilSections,
  cibilScoreBands,
  cardCollections,
  categoryPages,
  bestCardPicks,
} from '../src/data/content.js';

const esc = (v) => v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const lines = [];

lines.push('-- ============================================================');
lines.push('-- AUTO-GENERATED by scripts/generate-seed.mjs - do not edit.');
lines.push('-- Run supabase/schema.sql first, then this file.');
lines.push('-- ============================================================');
lines.push('');

// banks
lines.push('-- banks');
for (const b of banks) {
  lines.push(`insert into banks (id, name, logo_url) values (${esc(b.id)}, ${esc(b.name)}, ${esc(b.logo)});`);
}
lines.push('');

// categories
lines.push('-- card categories');
categories.forEach((c, i) => {
  const show = c.showInFilter === false ? 'false' : 'true';
  lines.push(`insert into card_categories (id, name, icon_url, show_in_filter, sort_order) values (${esc(c.id)}, ${esc(c.name)}, ${esc(c.icon)}, ${show}, ${i});`);
});
lines.push('');

// cards
lines.push('-- credit cards');
creditCards.forEach((card, i) => {
  lines.push(`insert into credit_cards (id, name, bank_id, image_url, joining_fee, annual_fee, sort_order) values (${card.id}, ${esc(card.name.trim())}, ${esc(card.bank)}, ${esc(card.image)}, ${card.joiningFee}, ${card.annualFee}, ${i});`);
});
lines.push('');

// card <-> category map (with extra assignments merged)
lines.push('-- card category map');
const validCategoryIds = new Set(categories.map(c => c.id));
for (const card of normalizeCards(creditCards)) {
  for (const catId of card.categories) {
    if (!validCategoryIds.has(catId)) {
      throw new Error(`Card ${card.id} references unknown category "${catId}"`);
    }
    lines.push(`insert into card_category_map (card_id, category_id) values (${card.id}, ${esc(catId)});`);
  }
}
lines.push('');

// benefits
lines.push('-- card benefits');
for (const card of creditCards) {
  card.benefits.forEach((b, i) => {
    lines.push(`insert into card_benefits (card_id, icon_url, benefit_text, position) values (${card.id}, ${esc(b.icon)}, ${esc(b.text.trim())}, ${i});`);
  });
}
lines.push('');

// collections
lines.push('-- card collections');
const cardIds = new Set(creditCards.map(c => c.id));
cardCollections.forEach((col, i) => {
  lines.push(`insert into card_collections (id, title, show_all_link, sort_order) values (${esc(col.id)}, ${esc(col.title)}, ${col.showAllLink}, ${i});`);
  col.cardIds.forEach((cardId, pos) => {
    if (!cardIds.has(cardId)) throw new Error(`Collection "${col.id}" references unknown card ${cardId}`);
    lines.push(`insert into card_collection_items (collection_id, card_id, position) values (${esc(col.id)}, ${cardId}, ${pos});`);
  });
});
lines.push('');

// best card picks
lines.push('-- best card picks');
bestCardPicks.forEach((p, i) => {
  if (!cardIds.has(p.cardId)) throw new Error(`Best pick references unknown card ${p.cardId}`);
  lines.push(`insert into best_card_picks (card_id, tagline, position) values (${p.cardId}, ${esc(p.tagline)}, ${i});`);
});
lines.push('');

// category pages
lines.push('-- category pages');
for (const p of categoryPages) {
  if (!validCategoryIds.has(p.categoryId)) throw new Error(`Category page "${p.slug}" references unknown category "${p.categoryId}"`);
  lines.push(`insert into category_pages (slug, title, category_id, description) values (${esc(p.slug)}, ${esc(p.title)}, ${esc(p.categoryId)}, ${esc(p.description)});`);
}
lines.push('');

// faqs
lines.push('-- faqs');
faqs.forEach((f, i) => {
  lines.push(`insert into faqs (page, question, answer, position) values (${esc(f.page)}, ${esc(f.q)}, ${esc(f.a)}, ${i});`);
});
lines.push('');

// interest rates
lines.push('-- interest rates');
interestRates.forEach((r, i) => {
  lines.push(`insert into interest_rates (bank_name, monthly_rate, annual_rate, position) values (${esc(r.bank)}, ${esc(r.monthly)}, ${esc(r.annual)}, ${i});`);
});
lines.push('');

// reviews
lines.push('-- reviews');
for (const r of reviews) {
  lines.push(`insert into reviews (name, location, review_text, rating) values (${esc(r.name)}, ${esc(r.location)}, ${esc(r.text)}, ${r.rating});`);
}
lines.push('');

// eligibility criteria
lines.push('-- eligibility criteria');
eligibilityCriteria.forEach((e, i) => {
  lines.push(`insert into eligibility_criteria (criterion, salaried, self_employed, position) values (${esc(e.criterion)}, ${esc(e.salaried)}, ${esc(e.selfEmployed)}, ${i});`);
});
lines.push('');

// cibil sections
lines.push('-- page sections (cibil-score)');
cibilSections.forEach((s, i) => {
  lines.push(`insert into page_sections (page, title, body, position) values ('cibil-score', ${esc(s.title)}, ${esc(s.body)}, ${i});`);
});
lines.push('');

// cibil score bands
lines.push('-- cibil score bands');
cibilScoreBands.forEach((b, i) => {
  lines.push(`insert into cibil_score_bands (score_range, rating, approval, position) values (${esc(b.range)}, ${esc(b.rating)}, ${esc(b.approval)}, ${i});`);
});
lines.push('');

// silence unused var warning for extraCategoryAssignments (merged via normalizeCards)
void extraCategoryAssignments;

const outPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'seed.sql');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');
console.log(`Wrote ${lines.length} lines to ${outPath}`);
